language: python

python:
  - "3.5"

cache: pip

os:
  - linux

notifications:
  email: false

addons:
  apt:
    packages:
      - gfortran

install:
  - python setup.py install

script:
  - python test/test.py
